language: php

php:
    - 7.0

env:
    - COMPOSER_ROOT_VERSION=2.0.0

install:
  - wget https://curl.haxx.se/ca/cacert.pem

before_script:
    - travis_retry composer self-update
    - travis_retry composer install

notifications:
    on_success: never
    on_failure: always

script: vendor/bin/phpunit

